project:
  type: website

website:
  title: "The Companion book a M1 MODE student should have!"
  subtitle: "At least, the one the M2 students wish they had"
  navbar:
    left:
      - icon: github
        href: https://github.com/MarieEtienne/MODE_reproduciblescience
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
    right:
      - text: Chapter 0: Introduction
        menu:
        - text: A simple text file 
          href: simple_chapter.qmd
        - text: A chapter using R
          href: r_chapter.qmd
        - text: A chapter using Python
          href: python_chapter.qmd
        aria-label: GitHub



format:
  html:
    theme: flatly
    highlight: tango
    toc: true
    
